# ==========================
# MySQL Database
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Groq AI
# ==========================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

spring.ai.retry.max-attempts=1

# ==========================
# Swagger
# ==========================
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================
# Resilience4j Retry
# ==========================
resilience4j.retry.instances.groqAi.max-attempts=3
resilience4j.retry.instances.groqAi.wait-duration=1s
resilience4j.retry.instances.groqAi.enable-exponential-backoff=true
resilience4j.retry.instances.groqAi.exponential-backoff-multiplier=2

# ==========================
# Circuit Breaker
# ==========================
resilience4j.circuitbreaker.instances.groqAi.sliding-window-size=10
resilience4j.circuitbreaker.instances.groqAi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.groqAi.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.groqAi.permitted-number-of-calls-in-half-open-state=2

# ==========================
# Time Limiter
# ==========================
resilience4j.timelimiter.instances.groqAi.timeout-duration=20s

# ==========================
# Rate Limiter
# ==========================
resilience4j.ratelimiter.instances.ai.limit-for-period=20
resilience4j.ratelimiter.instances.ai.limit-refresh-period=1m
resilience4j.ratelimiter.instances.ai.timeout-duration=0